### Example request using date range
GET http://localhost:3000/sales/report/start=2022-03-11&end=2022-03-12

### Example request using single date
GET http://localhost:3000/sales/report/start=2022-03-11